language: python
python:
  - "3.8.6"
env:
  -DJANGO=3.1.4 DB=postgresql
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run manage.py test
after_success:
  coveralls
