# Generated by Django 3.1.3 on 2020-12-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Воспоминание'),
        ),
    ]
